# Generated by Django 3.0.1 on 2020-01-20 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=64)),
                ('creadted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
