# Generated by Django 3.0.1 on 2020-01-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Post',
        ),
    ]
